login:
    path: /login
    defaults: {_ontroller: Evaluatorbundle:User:login}
    
login_check:
    path: /login_check

logout:
    path: /login

evaluator_homepage:
    path: /
    defaults: { _controller: EvaluatorBundle:Default:index }
