login:
    path: /login
    defaults: {_controller: EvaluatorBundle:User:login}
    
login_check:
    path: /login_check

logout:
    path: /logout

evaluator_homepage:
    path: /
    defaults: { _controller: EvaluatorBundle:Default:index }
